### ISSUE TITLE
background blur doesn't work when the url bar is in focus after the new update

### ISSUE THREAD

**Issue by Deathgrips0nline** [JLBlk/Zen-Themes#10]
**Affected Theme**
 - Name
 - Version (e.g. x.x.x)

**Affected Theme Settings**
- x

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by JLBlk** [comment]
Fixed with v1.1.1
