### ISSUE TITLE
[Bug] System auto theme overrides Super Gradient

### ISSUE THREAD

**Issue by heydoyouknowme0** [JLBlk/Zen-Themes#18]
**Affected Theme**
 - Name -Super Gradient 
 - Version - v1.1.0

**Affected Theme Settings**
- All

**Zen Version**: 1.0.1-a.5

**System OS**: Linux(fedora cosmic)

**Describe the bug**
When using the system auto theme the colors by the gradient gets overridden to default colors.

**To Reproduce**
1. Go to "addon and themes"
2. Click on Themes from the left side nav
3. Enable "System theme — auto" option

**Additional context**
This allows me to automatically switch to the dark/light mode also get default system buttons.

**Comment by heydoyouknowme0** [comment]
Can be zen issue it self [https://github.com/zen-browser/desktop/issues/1698](This)

**Comment by JLBlk** [comment]
Yeah, ig it's a zen issue, since other themes (color themes) have the same problem. Besides I don't know if I could fix it. 
I will close this for now, maybe i find a way someday, but now i dont really have the time, sry :(
