### ISSUE TITLE
[Feature Request] make pinned tabs go in 3's

### ISSUE THREAD

**Issue by Dreel0akl** [JLBlk/Zen-Themes#20]
hey there, im switching from arc to zen and one peeve i have is that in arc, i had my pinned tabs in a 3x3 order, but in zen pinned tabs go in 4's, could SuperPins add a way to change the sidebar around to allow this?

**Comment by JLBlk** [comment]
Hey, the number of pins per row is dynamic depending on the size of the sidebar/tabbar. So if you make it smaller/wider, there are less/more pinned tabs per row (the same way arc does it)

![image](https://github.com/user-attachments/assets/b6f1c42a-540b-4a08-b31c-87fb0024ca13)

Here. I also like the 3 pins per row and use it like that, just decrease the size of the sidebar :)

**Comment by Dreel0akl** [comment]
Is there any way to have the sidebar smaller and the icons more square, I’ve set it like this just now and it’s fine for now but I’m just wondering as I don’t want the sidebar to be too big.

**Comment by JLBlk** [comment]
Well, regarding the more square icons there is an option for that in the Mod Settings (if you mean that).
Regarding making the sidebar smaller while still having 3 Pins per row, i guess you could enable the compact margins setting, which gives you a tiny bit more headroom. If you know how to edit the source file of the mod you could change the width of the pins to your liking. 
Maybe I'll add a dropdown menu where one can set the width of pins in the future

**Comment by Dreel0akl** [comment]
Alright then, thank you!
