### ISSUE TITLE
[Bug] Theme makes (some) native UI components transparent

### ISSUE THREAD

**Issue by Numline1** [JLBlk/Zen-Themes#21]
**Affected Theme**
 - SuperGradient
 - Version (e.g. 1.1.0)

**Affected Theme Settings**
- Unsure

**Zen Version**: e.g "1.0.1-a.5"

**System OS**: e.g "macOS Sequoia 15.0"

**Describe the bug**
Some UI elements used by the browser are transparent. I haven't noticed this bug without the theme. One specific I'm seeing is basic auth prompt, see image. I'm using a custom gradient, but I believe I've seen this with the pre-populated ones too. It's difficult to see on the screenshot, since there's just a dark background, but the modal itself has no background, which looks weird on other websites.

**To Reproduce**
1. Go to 'any page with basic auth, I currently don't have any public on hand :('

**Expected behavior**
The element should either have a simple background color and/or use the selected gradient.

**Screenshots/Videos**
![Screenshot 2024-09-28 at 23 36 01](https://github.com/user-attachments/assets/e9cfa9a2-7c67-4500-a73a-5f2af4c913b1)

**Comment by JLBlk** [comment]
Thanks for reporting it. One question: Would you prefer it to take on the gradient or just the default zen color?
