### ISSUE TITLE
[Bug] Compact floating sidebar, not showing gradient

### ISSUE THREAD

**Issue by mbr67** [JLBlk/Zen-Themes#22]
In the latest (v. 1.1.1) the sidebar with the module floating compact -sidebar (v. 1.0.0) is not showing the gradients (colors).
Thanks

**Comment by JLBlk** [comment]
Yeah, i know. After zen's a.6 update using --zen-colors-tertiary isn't possible anymore, which was the only way (i know of) i was able to apply the gradient to floating mode. Maybe i'll find another way in the future, but i wouldn't put my hopes up, sry

**Comment by mbr67** [comment]
Is there a way you know to make it acrylic with mica for windows?
