### ISSUE TITLE
[Feature Request] Should increase the blur intencity 

### ISSUE THREAD

**Issue by ptdatta** [JLBlk/Zen-Themes#24]
**The related Mod/Theme:**

**Your Enhancement Suggestion/Feature Request**
https://github.com/JLBlk/Zen-Themes/blob/210fe15877d7d0b6b25ee2cae8c730ef2e31db7d/SuperUrlBar/SuperUrlBar.css#L56

`6px` will be a good value.

**Comment by JLBlk** [comment]
Good idea, thanks,  i'll do that when i have the time.
But i'll implement it as a dropdown so the user can choose the intensity.

**Comment by JLBlk** [comment]
I implemented it as a dropdown with 5 options, where your 6px is the strongest blur intensity, will be available as soon as the pull request above gets merged :)
Thanks a lot for the suggestion again!
