### ISSUE TITLE
[Feature Request] Ability to add buttons to URL Bar

### ISSUE THREAD

**Issue by YouCanTouCan** [JLBlk/Zen-Themes#26]
**The related Mod/Theme:** SuperURLBar

**Your Enhancement Suggestion/Feature Request**
This Zen Mod already has the ability to remove icons from the URL Bar, but it would be nice for it to also add the ability to place icons inside of the URL Bar that otherwise couldn't be.

For example, I commonly use the addon [ToS;DR](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) as well as [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), and for both of these but especially the former I feel like it fits to have their icons placed inside the URL bar - on the far right side of it or the far left side of it, respectively. This allows uBlock Origin to then exist next to the shield icon, and ToS;DR to provide more info on the website too (past versions of the extension could be placed in the URL Bar without custom CSS, but this was unfortunately removed). I have traditionally used the following CSS code to achieve this - with it, any button placed directly right of the URL Bar will be moved inside it. Credit for the code goes to [this old CSS theme](https://github.com/soulhotel/Perfection-Firefox-CSS-Theme).
```
#urlbar {padding-inline-end: calc(17px + 2 * var(--urlbar-icon-padding));}
#urlbar-container+.chromeclass-toolbar-additional{
margin-inline-start: calc(0px - 19px - 2 * var(--urlbar-icon-padding) - var(--urlbar-margin-inline)) !important;
position: relative;
--toolbarbutton-inner-padding: var(--urlbar-icon-padding);
--toolbarbutton-hover-background: var(--urlbar-box-hover-bgcolor);}
```
To clarify, this is of course not just for these two specific addons I use - they work for any button that the user can move the location of. It may be possible to edit this to do the same thing but with the left side of the URL bar as well, I've never worked out how to do it myself, admittedly.

I admit this CSS may be extremely niche, and others besides me might not have a use for it, but on the off-chance you think it would fit your mod (thank you so much for your constant work on it) I thought I would submit it as a request, especially as I have the code already. I find it makes the top bar feel cleaner somehow, which fits nicely with the purpose of your amazing mod.

**Comment by JLBlk** [comment]
Hey, first of all thx for the kind words. 
I really liked your idea and implemented it as an option in the mod. It will be publicly available as soon as the pull request linked above is merged :)
Thx a lot for the suggestion and the code! (i only adjusted the code a bit so that the moved button doesn't overlay with the bookmark star button)
