### ISSUE TITLE
[SuperGradient] Gradient in new tab

### ISSUE THREAD

**Issue by konfitti** [JLBlk/Zen-Themes#31]
**SuperGradient**

**Gradient in new tab**

I think the gradient should continue in new tab. It may be can done with making transparent the new tab background.

![image](https://github.com/user-attachments/assets/8f48099d-3c5b-4881-a548-d9b61904be6c)
While loading a random new tab the background looks like this, therefore it may be can done with making the new tab background transparent .

**Comment by JLBlk** [comment]
Sry, but i couldn't find a way to make that possible in a mod, since using userContent.css isn't supported in mods yet, which seems to be required for any edits on the new-tab page, sry

Duplicate of https://github.com/JLBlk/Zen-Themes/issues/11
