### ISSUE TITLE
[Feature Request] Option to alway open websites in new tabs when using Url Bar

### ISSUE THREAD

**Issue by AlexanderGson** [JLBlk/Zen-Themes#32]
**The related Mod/Theme:**

Super URL Bar

**Your Enhancement Suggestion/Feature Request**

I'd like an option in the settings to be able to always open websites in new tabs when using the URL Bar.

Instead of Zen/Firefox standard behavior of opening either opening a new tab with CTRL+T and then CTRL+L to open the URL bar. Or CTRL+L and ALT+Enter to open in new tab. This way I could rebind CTRL+L to CTRL+T and use the Super URL Bar to enter my website and in a new tab.

**Comment by JLBlk** [comment]
Great idea, i'll add it as an option with the next version. Thanks for the suggestion!
