### ISSUE TITLE
[Feature Request] [SuperGradient] Add ability to customise gradient per workspace

### ISSUE THREAD

**Issue by djeglin** [JLBlk/Zen-Themes#33]
**The related Mod/Theme:** SuperGradient

**Your Enhancement Suggestion/Feature Request**
It would be incredibly useful for me, and I would assume some others who regularly use workspaces to have separate profiles for various clients etc, to be able to customise the gradient of the theme on a per-workspace level. This would mean that I could have a primarily green gradient for one client, and a primarily red gradient for another, as an example. As an at-a-glance way to know which workspace you are in, it would be incredibly useful.

**Comment by JLBlk** [comment]
Hey, sry for the late answer first of all.
i love the idea, but unfortunately this isn't possible due to the limitations of zen mods.
However Zen is getting a native implementation of Gradients (and workspace specific gradients iirc) really soon!
