### ISSUE TITLE
[Bug] Hidden Buttons are still Clickable

### ISSUE THREAD

**Issue by YouCanTouCan** [JLBlk/Zen-Themes#34]
**Affected Theme**
 - Super URL Bar
 - Version 1.3.0

**Affected Theme Settings**
- All "Hides the..." options enabled, "Make the hidden icons show when hovering the url bar" disabled. Occurs regardless of the other settings.

**Zen Version**: 1.0.1-a.9 (64-bit) (flatpak)

**System OS**: Aurora (an edited image of Fedora Kionite)

**Describe the bug**
When icons are hidden, they are visually gone but are still clickable. This can even lead to having an invisible button on top of a visible button, blocking the visible button from being clickable.

**To Reproduce**
1. Go to the zen mod settings
2. Hide the shield icon and the bookmark icon (as these are the easiest ones to test with)
4. Go onto any website
4. Click on the far right side of the url bar, where the shield icon would be if it was visible. Note the shield icon window appearing.
5. Ctrl + Left Click on any two tabs to select both
6. Right Click on one of the tabs selected
7. Select "Split Two Tabs" to enable split tabs. The split tabs button will now appear on the far right of the URL Bar
8. Click the split tabs button in the URL Bar. Note that instead of the split tabs window appearing, the bookmark window does.

**Expected behavior**
Buttons within the URL Bar should only be clickable when they are visible - enabling the option to hide them should make them completely unusable, not just invisible.

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/78e99d9e-5919-4619-8f27-7c011da38760)
![image](https://github.com/user-attachments/assets/83a1cb89-8f4c-4e95-92d9-30b1becf846f)

**Additional context**
I tried these steps in a new zen browser profile with no other mods or css active, and still achieved the results listed.

**Comment by YouCanTouCan** [comment]
I just realized this appears to be the same as [#28](https://github.com/JLBlk/Zen-Themes/issues/28). My apologies, feel free to close this if you deem it correct to do so. Hopefully this additional context about the issue helps.

**Comment by JLBlk** [comment]
Yeah, seems like they're similar. But i honestly can't reproduce the other one (i can't make the star visually appear). This one however i can reproduce. 
Thanks a lot for the detailed report! 
I'll have a look into it when i have the time

**Comment by ProbablyM-S** [comment]
I am also having this issue. I can confirm.

**Comment by JLBlk** [comment]
Yeah, i already have a working fix ready, will be available with the next update (might still take a bit though, since i also wanna fix some other things)
