### ISSUE TITLE
[Bug] Problems with borders on youtube

### ISSUE THREAD

**Issue by hannylord** [JLBlk/Zen-Themes#36]
**Affected Theme**
 - SuperGradient Mod
 - Version 1.2.1

**Affected Theme Settings**
- Overall
![image](https://github.com/user-attachments/assets/ede8e6a6-a34d-4b8d-8aef-083b43558ef7)

**Zen Version**: Idk (latest, it was downloaded today)

**System OS**: Winodws 11

**Describe the bug**
When the mod is turned on, the borders on youtube are squares.
I've turned the mod off and everything is fine again, so the problem is connected with SuperGradient.

**To Reproduce**
1. Enable the mod
2. Visit youtube.com

**Expected behavior**
The borders should be rounded like on other sites.

**Screenshots/Videos**
Difference:
![image](https://github.com/user-attachments/assets/60bad5a1-2c89-4889-a825-d52b9bf772f2) — youtube
![image](https://github.com/user-attachments/assets/f0409677-d6c3-4606-85d0-e356f0113774) — twitch

**Additional context**
None.

**Comment by JLBlk** [comment]
Closing due to the removal of SuperGradient from the mods (since there is a native Implementation of gradients now)
