### ISSUE TITLE
Make superpin have 3 tabs at most in one ROW

### ISSUE THREAD

**Issue by greed-d** [JLBlk/Zen-Themes#4]
![image](https://github.com/user-attachments/assets/8de7fa8a-4749-4372-8c30-dfb0c3959c76)

As you can see here, super pins have 5 tabs in one row, I'd like some behavior to make it show 3 or 2 pinned tabs at most according to the width of sidebar.

**Comment by JLBlk** [comment]
Hi, you are currently using zen version a35, right? The theme is currently broken in this version, but i already fixed it and the pull request is waiting for approval (https://github.com/zen-browser/theme-store/pull/322). Regarding your wish, can you please specify your wished bavior? 

https://github.com/user-attachments/assets/7e59e38a-8e37-4467-96d9-2ed4d18e954a

This is the current behavior (the same you will get when the pr got approved to fix the theme after a35 update). It dynamically adapts the number of pinned tabs per row based on the sidebar width so you can basically controll the number of pins per row. Do you want to have a global limit of like 3 pinned tabs per row no matter how wide the sidebar is or what exactly?

**Comment by greed-d** [comment]
Yes, that's the behavior I'm looking for, thanks, for now I'll just be doing copy pasta magic 

Closing this issue

**Comment by greed-d** [comment]
reopening this as superpin breaks the expand on hover option
