### ISSUE TITLE
[Bug] Reorganizing Pins Clunky > Dragging Existing Pin, if new window is created, removes the pinned tab. 

### ISSUE THREAD

**Issue by evanrdlc** [JLBlk/Zen-Themes#40]
**Affected Theme**
 - Superpins
 - Version (e.g. v1.3.6)

**Affected Theme Settings**
- Superpins

**Zen Version**: 1.0.1-a.12

**System OS**: "Windows 11"

**Describe the bug**
When reorganizing the tabs, 

**To Reproduce**
1. Create multiple pinned tabs
2. Drag one of them trying to re-order them, but intentionally drag it away from the superpins area.
3. You'll notice that the pinned tab you were trying to re-organize opened in a new window. 
4. Go back to original window, observe that the pin was removed.

**Expected behavior**
Ideally, when I am dragging my pins to re-order them, the experience would be easier to use.
But in the existing behavior, I would expect that:
1. Dragged pins only re-order them, and do not open new windows.
2. If the pin was opened in a new window, it at least wouldn't be removed from the superpins.

**Screenshots/Videos**
N/A

**Additional context**
N/A

**Comment by JLBlk** [comment]
Hey, unfortunately this isn't a bug of SuperPins but from Zen itself. Mods (like SuperPins) only change the visuals of the browser, they can't change the logic of it (yet), sry
