### ISSUE TITLE
[Bug] Right Click > Close Tab Removes from SuperPins

### ISSUE THREAD

**Issue by evanrdlc** [JLBlk/Zen-Themes#41]
**Affected Theme**
 - Superpin
 - Version (1.3.6)

**Affected Theme Settings**
- Regular Functionality

**Zen Version**: 1.0.1-a.12

**System OS**: Windows 11

**Describe the bug**
When I right click > Close Tab on a superpin:
1. The tab is removed from superpins.
2. The tab is also closed.

**To Reproduce**
1. Create a superpin
2. Right Click > Close Tab
3. Observe

**Expected behavior**
I would expect the pin to remain in the superpin area, but that the tab would be closed.

**Screenshots/Videos**
N/A

**Additional context**
N/A

**Comment by JLBlk** [comment]
Hey, unfortunately this also isn't a problem of SuperPins but of Zen itself. Mods (like SuperPins) can only change the visual appearance of the browser and not any logic (yet), sry
