### ISSUE TITLE
[Bug] Blur applied without interacting with ULR toolbar

### ISSUE THREAD

**Issue by Redcupss** [JLBlk/Zen-Themes#42]
**Affected Theme**
 - Super URL Bar
 - Version v1.4.0

**Affected Theme Settings**
- Enable background blur when Url bar is focused & select it's intensity

**Zen Version**: Version 1.0.1-a.12 (64-bit)

**System OS**: MacOS 14.4.1 (23E224)

**Describe the bug**
The setting seems to apply blur over the window, specifically noticeable over text. Any of the settings except 'off' make this happen. It goes away when you highlight text, but everything else remains blurred.

**To Reproduce**
1. Go to mod setting titled "Enable background blur when Url bar is focused & select it's intensity"
2. Click on any option, like subtle or strong. They all have the same error.
3. You should see the blur take effect immediately over the rest of the text on the window. 

**Expected behavior**
No blur should be visible until the URL toolbar is clicked on

**Comment by JLBlk** [comment]
Hmm weird, could you maybe send a quick screenshot? I really don't have any idea how this could happen and since i can't reproduce the issue, it's rather hard to fix. Did you also try it on a new profile?

**Comment by Redcupss** [comment]
Sure thing:

With blur setting on:
<img width="1880" alt="Screenshot 2024-10-27 at 20 13 40" src="https://github.com/user-attachments/assets/427dafd1-9920-4ae7-8498-5f72d54018a2">
<img width="829" alt="Screenshot 2024-10-27 at 20 14 07" src="https://github.com/user-attachments/assets/b3f422d3-cd6c-405f-a063-ce3c2bf4b0d3">

Blur setting off:
<img width="804" alt="Screenshot 2024-10-27 at 20 13 56" src="https://github.com/user-attachments/assets/9fde7e34-dab5-498e-a7b1-9c51c72a4df8">
<img width="1867" alt="Screenshot 2024-10-27 at 20 13 45" src="https://github.com/user-attachments/assets/a3d14fdc-01cd-46cb-9d0d-54ed8204009e">

**Comment by Redcupss** [comment]
Blur setting on: 
<img width="804" alt="Screenshot 2024-10-27 at 20 13 56" src="https://github.com/user-attachments/assets/0fc53081-0d93-4f67-9f46-fe793f016183">
<img width="1880" alt="Screenshot 2024-10-27 at 20 13 40" src="https://github.com/user-attachments/assets/15595a73-ecc8-4d13-9253-a099a6481447">

Blur setting off:
<img width="829" alt="Screenshot 2024-10-27 at 20 14 07" src="https://github.com/user-attachments/assets/de333821-4f82-40ee-85ef-b3edd5bd2d78">
<img width="1867" alt="Screenshot 2024-10-27 at 20 13 45" src="https://github.com/user-attachments/assets/a0484c6e-9b6f-496e-b5f5-acb664cb4a7b">

**Comment by Redcupss** [comment]
These images aren't the highest resolution - they aren't the sharpest but you can see the effect along the edges of letters

**Comment by Redcupss** [comment]
These images are on a new profile btw. Sorry for the separate posts.

**Comment by Redcupss** [comment]
Okay I narrowed it down some more. This only happens when the browser window is stretched to almost fullscreen. I saw some other people in the Zen Browser discord were having the same blurring issue and the fix was to toggle the about:config setting zen.view.experimental-rounded-view to false. That fixes the problem when Super Url Bar Background Blur setting is off. But it stills blurs everything when background blur is on.

**Comment by JLBlk** [comment]
Ok, all of this sounds a lot like the clip-path is the problem. I needed to "enable" clip-path to get the background blur working, i don't really know exactly why these two things are so connected, but the blue didn't work without the clip-path. 
However I tested this again now and it seems that with the new zen version the background blur seems to be working without the clip path, so ig i'll hopefully fix it then. I'll reply to this again, when the update for the mod is through to ask you if it changed.
Thanks A LOT for the investigation!

**Comment by JLBlk** [comment]
Hey, could you maybe update the mod and test the issue again? I removed clip-path now, which was my only guess that could cause this.

**Comment by Redcupss** [comment]
Hey, I updated and tried it out. The overall blur is fixed but it seems like there's probably a bigger issue with firefox or zen because the background blur setting in your mod only works as intended when I switch the about:config experimental.rounded.view to true. But then changing that to true is what causes the overall application to blur fonts badly. 

I'll break it down this way to give an idea of why I say that:

If,
Super URL background blur: Off
About:Config experimental-rounded-view: True
Then, everything is pretty much blurred badly

If,
Super URL background blur: Off
About:Config experimental-rounded-view: False
Then, nothing is blurred

If,
Super URL background blur: On
About:Config experimental-rounded-view: False
Then, nothing is blurred (cause you fixed that) but the SuperURL background blur setting doesn't do anything. It just opens the URL bar normally with no background blur applied as intended

If,
Super URL background blur: On
About:Config experimental-rounded-view: True
Then, everything is blurred and the bg blur setting works as intended when you open the URL bar.

I don't think there's anything wrong with your mod tbh. But if you have any advice, I'm all ears
