### ISSUE TITLE
[Feature Request] Option to allow SuperPin to be full width and with text

### ISSUE THREAD

**Issue by microBob** [JLBlk/Zen-Themes#46]
**The related Mod/Theme:** SuperPin

**Your Enhancement Suggestion/Feature Request**
I'm coming from Arc and heavily use the feature of pinning tabs and using them as per-workspace bookmarks. It would be great if there was an option to let SuperPin'd tabs be full width (like a normal tab) and also have the tab's text be available.

Thanks!

**Comment by JLBlk** [comment]
Hey, good news, Zen is currently implementing that, really similar to the way arc does it. afaik it will be available with the next zen release! Here a little preview:
![image](https://github.com/user-attachments/assets/e0485e7a-dfa5-4754-943a-fedc4829385b)

**Comment by kjy5** [comment]
Oh nice! I did not realize this. Thank you!

**Comment by microBob** [comment]
Oh nice! I did not realize this. Thank you!
