### ISSUE TITLE
Add background to pin tabs

### ISSUE THREAD

**Issue by justingallant1988** [JLBlk/Zen-Themes#47]
With the arrival of essentials, the light background on pinned tabs no longer shows. SuperPins provides an option to add a border, but can we also have an option to add the old background that used to exist? Currently essentials still shows a background but pins no longer have a background. Just an icon or just a border option makes the visibility not ideal.

![CleanShot 2024-11-09 at 17 37 00@2x](https://github.com/user-attachments/assets/a9f6c60d-4796-4fa7-982f-d41b06afdbec)

**Comment by JLBlk** [comment]
Thanks for the idea! implemented it instantly, just update the mod
