### ISSUE TITLE
X icon removed when SuperPins is active

### ISSUE THREAD

**Issue by justingallant1988** [JLBlk/Zen-Themes#48]
1.0.1-a.18

MacOS

The X icon disappears from the regular tab when Superpins is activated.

**Comment by mafolab1** [comment]
Same issue, I've discovered it happens when the option `Makes pinned tabs look similar to Essentials (icon only in a grid)` is enabled.

**Comment by poulpor** [comment]
Same issue, MacOS too.

**Comment by octenite** [comment]
Same issue also present on the windows version too . It is triggered when enabling "Makes pinned tabs look similar to Essentials (icon only in a grid)"

**Comment by JLBlk** [comment]
Yeah, sry about that. Forgot to specify in the code so that the x button is only hidden from pinned tabs and not normal one, will fix asap

**Comment by poulpor** [comment]
Thank you very much for the quick fix, Close buttons are back!
