### ISSUE TITLE
[Bug] Expand on Hover broken when leaving window with mouse

### ISSUE THREAD

**Issue by greed-d** [JLBlk/Zen-Themes#5]
When using the option "expand on hover" with superpins, there is this jitteriness that moves webpage along with the sidebar, which isn't the behavior in zen-browser

**Comment by JLBlk** [comment]
Yeah i just noticed, i'll look into it, thanks

**Comment by greed-d** [comment]
thanks

**Comment by JLBlk** [comment]
I fixed it now, the pr is pending.

**Comment by greed-d** [comment]
reopening this as it happens again

**Comment by greed-d** [comment]
https://github.com/user-attachments/assets/33451c26-2aaa-4631-b5ac-3c36c5ffe7f8

**Comment by JLBlk** [comment]
The jitter in general seems to be a bug of Zen itself, since last update added some things to make it easier to work with compact mode (and expand on hover). I don't think i can do anything about it right now, sry :(

**Comment by greed-d** [comment]
> The jitter in general seems to be a bug of Zen itself

Hmm, but that doesn't happen when I'm not using superpins? or am I missing something here?

**Comment by JLBlk** [comment]
Yeah sry, I originally meant this jitter 

https://github.com/user-attachments/assets/ef9d94fe-1233-4e6f-90fd-e1829f3af6c0

Now that I'm thinking about it more, i may be able to adjust the way the mod detects the hover on expand on hover. I'll look into it when i have the time, sry for the inconvenience
