### ISSUE TITLE
[Bug] SuperPins (v1.4.0) - Selecting "Makes pinned tabs look similar to Essentials (icon only in a grid)" Removes close icon from normal tabs

### ISSUE THREAD

**Issue by SilentUK90** [JLBlk/Zen-Themes#50]
**Affected Theme**
 - SuperPins
 - Version (v1.4.0)

**Affected Theme Settings**
- Makes pinned tabs look similar to Essentials (icon only in a grid

**Zen Version**:  "1.0.1-a.18"

**System OS**:  "Windows 11"

**Describe the bug**
When selecting the option "Makes pinned tabs look similar to Essentials (icon only in a grid", all normal tabs will lose the close "X" icon on the right hand side making them only possible to be closed with mouse wheel click.

**Screenshots/Videos**
Without Options Ticked:

![image](https://github.com/user-attachments/assets/d6b0332e-3ccc-4e02-a171-561c419f4a6d)

With Option Ticked:

![image](https://github.com/user-attachments/assets/45c01731-fe76-4cb4-95a0-d43521d7ad28)

**Comment by JLBlk** [comment]
Yeah, sry about that, forgot an identifier in the code. It's fixed already thanks to @cheeeebs . The fix is available as soon as the pr (https://github.com/zen-browser/theme-store/pull/742) is approved.
