### ISSUE TITLE
[Bug] Restoring pinned tabs to legacy layout does not work immediately in SuperPins unless I modify another mod setting.

### ISSUE THREAD

**Issue by seanballais** [JLBlk/Zen-Themes#52]
**Affected Theme**
 - SuperPins
 - Version (e.g. 1.4.1)

**Affected Theme Settings**
- Setting pinned tabs to legacy layout

**Zen Version**: e.g "1.0.1-a.19"

**System OS**: e.g "Windows 11"

**Describe the bug**
Unable to put set the pinned tabs to the legacy layout when you click the "Makes pinned tabs look similar to Essentials (icon only in a grid)" checkbox. You will have to modify another setting just for the changes to appear. Afterwards, the bug can no longer be replicated. Note that I just upgraded from `1.0.1-a.18`.

**To Reproduce**
1. Open the settings for SuperPins.
2. Check "Makes pinned tabs look similar to Essentials (icon only in a grid)".
3. See that the pins have not been updated.

**Expected behavior**
I was expecting that the pinned tabs would immediately be set to the legacy layout.

**Comment by seanballais** [comment]
Hey, @JLBlk! There is a chance this was a bug caused by upgrading Zen.

**Comment by JLBlk** [comment]
Yeah, most likely. I don't think I change anything that could've cause this. I'll close this for now, but if you ever encounter it again (and reproducable) please let me know/write in this issue again
