### ISSUE TITLE
[Bug] Pinned Tabs no longer in a grid.

### ISSUE THREAD

**Issue by shaqaruden** [JLBlk/Zen-Themes#54]
**Zen Version**: "1.0.1-a.19"

**System OS**: Windows 11

**Describe the bug**
Pinned Tabs are a list instead of a grid. Bug with a19?

I tried disabling all my other mods just in case of them was causing the issue but I was able to confirm they are not.

**To Reproduce**
1. Update to a19???

**Expected behavior**
Tabs to be in a 3-column grid

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/03767467-cae7-4fba-befb-20caebcedf10)

**Additional context**
Looks like the default layout for pinned tabs changed, this could be the cause

**Comment by orbi-tal** [comment]
Update your mods, there's a setting for this.

**Comment by shaqaruden** [comment]
lookin good!
