### ISSUE TITLE
[Bug] SuperPins removes normal tabs close button

### ISSUE THREAD

**Issue by Evthestrike** [JLBlk/Zen-Themes#58]
**Affected Theme**
 - SuperPins
 - Version 1.4.0

**Affected Theme Settings**
- Makes pinned tabs look similar to Essentials (icon only in a grid)

**Zen Version**: 1.0.1-a.19

**System OS**: Arch Linux

**Describe the bug**
The intended behavior is that the close button of only pinned tabs would be removed  since they are now in an icon grid. Instead, the close buttons of both the pinned and the non-pinned tabs are removed.

**To Reproduce**
1. Set the affected setting
2. *Witness the problem*
3. Unset the affected setting
4. *Problem goes away*

**Screenshots/Videos**
https://github.com/user-attachments/assets/f4606829-f072-4c80-9baa-41fd8f8a756d

**Comment by Evthestrike** [comment]
Somehow it's fixed? I don't know what changed in 1 hour

**Comment by Evthestrike** [comment]
I was having this issue since I updated to 1.0.1-a.19

**Comment by JLBlk** [comment]
Yeah, i forgot sth in superPins v1.4.0 that caused this, but with v1.4.1 it was fixed. You probably updated your mods (or they did it automatically), that's why it's fixed now
