### ISSUE TITLE
The latest versions of SuperPin are not listed correctly on the Zen Themes page

### ISSUE THREAD

**Issue by vk2r** [JLBlk/Zen-Themes#6]
Both version 1.2.0 and 1.3.0 are not listed correctly.
Even when installing 1.2.0, in the list of Zen extensions, it is listed as 1.1.0.

**Comment by JLBlk** [comment]
Hi, 1.3.0 isn't actually out yet, the pr is still waiting for approval before being pushed to everyone (here the pr: https://github.com/zen-browser/theme-store/pull/322). Regarding the wrong versions being displayed, i unfortunately cant help you with that. When updating a theme i simply increase the version number inside a json file. The displaying is being handled by Zen itself. For me it actually shows v 1.2.0 at the theme website or inside zens theme settings. The only suggestion i have is to update to latest zen version (a37) if not done already, sry
