### ISSUE TITLE
[Bug] The URL cursor goes always beginning of the URL

### ISSUE THREAD

**Issue by berkaykrc** [JLBlk/Zen-Themes#61]
**Affected Theme**
 - Name - [Super URL Bar](https://zen-browser.app/themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6)
 - Version v1.4.2
 
**Settings**
![image](https://github.com/user-attachments/assets/b67e27d0-a423-4394-8e24-8ead40a2dbda)

**Zen Version**: Version 1.0.1-a.19 (64-bit)

**System OS**: e.g "Windows 10"

**Describe the bug**
When focused on the URL bar it doesn't matter where you clicked the beginning of the URL or the end of it.

**To Reproduce**
1. Go to the URL bar
2. Click on URL
3. It automatically goes to the beginning of the URL

**Expected behavior**
It should go where the cursor is or if it's towards the end or beginning it should go respectively.

**Comment by JLBlk** [comment]
First of all sry for the late answer, been quite busy.
The issue sound more something like zen related that related to this mod, since I never changed anything that relates to that issue. Idk if it's changed in recent Zen versions now since it's been a while, so i'll close the issue for now
