### ISSUE TITLE
[Feature Request] [SuperPins] Option to remove "reset pinned tab" icon

### ISSUE THREAD

**Issue by whitelotuz** [JLBlk/Zen-Themes#66]
The option to make pinned tabs look like essentials works great...
![image](https://github.com/user-attachments/assets/d8cffaf9-929e-40a1-a2ac-b358f30f0f04)

However, when hovering to click on them the "reset pinned tab" arrow icon takes roughly 50% of the space of the button, making it 50/50 chance to either go to the pinned tab (desired outcome) or accidentally resetting the pinned tab (frustrating when not intended).
![image](https://github.com/user-attachments/assets/45fa7253-cb9d-4a32-b255-3dc9f631e915)

Having an extra checkbox in the mod settings to remove this on-hover icon would be great considering the feature itself is still available anyway if you right-click the pinned tab
![image](https://github.com/user-attachments/assets/0717bf9b-3b3b-4897-890d-160a82b19696)

**Comment by limonkufu** [comment]
yes half of the time I am hitting the reset icon instead of the actual tab because of the recent changes. This improvement would be great!

**Comment by limonkufu** [comment]
Hi I have submitted a PR #67 to add this capability. In the meantime anyone can just disable them by doing below:

1. Follow the steps to enable userChrome.css file (you have to restart the browser once the file is there): https://docs.zen-browser.app/guides/live-editing
2. Add this to your `userChrome.css`

```
#vertical-pinned-tabs-container .tab-reset-button {
    display: none !important;
}
```

**Comment by JLBlk** [comment]
Thanks for the pr, will add it to the store asap

**Comment by whitelotuz** [comment]
Thank you both, new update works as expected! Feel free to mark this one done, happy holidays!

**Comment by whitelotuz** [comment]
Thank you both, new update works as expected! Feel free to mark this one done, happy holidays!
